# GitHub Actions CI script for mkpsxiso
# (C) 2021 spicyjpeg

name: Build mkpsxiso
on:   [ push, pull_request ]

jobs:
  build-windows:
    name:    Build mkpsxiso on Windows
    runs-on: windows-latest

    steps:
    - name: Add MSys2 to PATH
      run: |
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install prerequisites
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc

    - name: Fetch repo contents
      uses: actions/checkout@v2
      with:
        path: mkpsxiso

    - name: Update repo submodules
      run: |
        cd mkpsxiso
        git submodule update --init --recursive --remote

    - name: Build and package mkpsxiso
      run: |
        cmake --preset ci -S mkpsxiso
        cmake --build build
        cmake --build build -t package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mkpsxiso-windows
        path: |
          build/packages/*
          !build/packages/_CPack_Packages

  build-linux:
    name:    Build mkpsxiso on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends build-essential ninja-build

    - name: Fetch repo contents
      uses: actions/checkout@v2
      with:
        path: mkpsxiso

    - name: Update repo submodules
      run: |
        cd mkpsxiso
        git submodule update --init --recursive --remote

    - name: Build and package mkpsxiso
      run: |
        cmake --preset ci -S mkpsxiso
        cmake --build build
        cmake --build build -t package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mkpsxiso-linux
        path: |
          build/packages/*
          !build/packages/_CPack_Packages

  # This job takes care of creating a new release and upload the build
  # artifacts if the last commit is associated to a tag.
  create-release:
    name:    Create release
    runs-on: ubuntu-latest
    needs:   [ build-windows, build-linux ]

    steps:
    - name: Fetch build artifacts
      if:   ${{ github.ref_type == 'tag' }}
      uses: actions/download-artifact@v2
      with:
        path: .

    - name: Publish release
      if:   ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        #generate_release_notes:  true
        files: |
          *.zip
          mkpsxiso-windows/*
          mkpsxiso-linux/*
